-- Add up migration script here
CREATE TABLE IF NOT EXISTS KIFU (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    WINNER INTEGER NOT NULL,
    GENERATION INTEGER NOT NULL,
    RECORDS BINARY NOT NULL
);